#- colon
#- control_statement
#- file_length
#- force_cast
#- function_body_length
#- leading_whitespace
#- line_length
#- nesting
#- operator_whitespace
#- return_arrow_whitespace
#- todo
#- trailing_newline
#- variable_name_max_length
#- variable_name_min_length
#- type_body_length
#- variable_name

disabled_rules:
- trailing_whitespace
- type_name
- todo

line_length: 300

excluded:
- Pods

type_body_length:
- 200 # warning
- 400 # error

variable_name_max_length:
- 60 # warning
- 80 # error

variable_name_min_length:
- 1 # warning
- 0 # error

function_body_length:
- 100 # warning
- 200 # error

